### PR TITLE
Add Baidu Speech Recognition API——Python 3

### PR DESCRIPTION
**Pull request by Decalogue**
Dear Zhang
       Hello! Thank you very much for your open source library, it has brought me a lot of convenience. I have used the Baidu speech recognition API recently, would like to review if these content modification can be joined. Thank you very much！
Best wishes
Decalogue(Rain)

### CODE REVIEW

**Comment by jhoelzl** [comment]
@Decalogue , thanks for improving, could you please translate all Chinese comments into English? Thanks!

**Comment by Decalogue** [comment]
@jhoelzl Thank you!

**Comment by Decalogue** [comment]
@jhoelzl Thanks for your advice and encouragement! I just improved it. Please check it. Thank you!

**Comment by Uberi** [comment]
Hi @Decalogue,

Thanks for looking into this! Unfortunately, we can't add this, because Baidu accounts can [only be made using a mainland China phone number](https://passport.baidu.com/v2/?reg&tpl=open_audio&u=http://yuyin.baidu.com/docs/asr). That means if Baidu ever changes their API, we won't have the ability to fix this library.

You may want to instead submit your changes to [PyBaiduYuyin](https://github.com/DelightRun/PyBaiduYuyin), a fork of this library that focuses exclusively on Baidu's speech recognition technology. Also, consider revoking your personal API keys - it might be a bad idea to expose those to the world!

**Comment by Decalogue** [comment]
@jhoelzl Thank you!

**Comment by Decalogue** [comment]
@Uberi Thank you!

**Pull request closed without merging**
