### PR TITLE
Tensorflow

### PR DESCRIPTION
**Pull request by chriamue**
Tensorflow audio commands recognition as shown here: https://www.tensorflow.org/versions/master/tutorials/audio_recognition
Model and Label file can be downloaded here: http://download.tensorflow.org/models/speech_commands_v0.01.zip

An example can be like this:
import speech_recognition as sr
r = sr.Recognizer()
m = sr.Microphone()
def callback(recognizer, audio):
    try:
        spoken = recognizer.recognize_tensorflow(audio, tensor_graph='speech_recognition/tensorflow-data/conv_actions_frozen.pb', tensor_label='speech_recognition/tensorflow-data/conv_actions_labels.txt')
        print(spoken)

with m as source:
    r.adjust_for_ambient_noise(source)
stop_listening = r.listen_in_background(m, callback, phrase_time_limit=1)

### CODE REVIEW

**Comment by Uberi** [comment]
Hi @chriamue,

Looks good to me! If you're done with this PR, I'd be happy to merge it. I did notice you also have a `deepspeech` branch, so if you'd rather merge that one, just let me know.

**Comment by chriamue** [comment]
I cannot fix following error, because without this import the given graph can not been used.

$ flake8 --ignore=E501,E701 speech_recognition tests examples setup.py
speech_recognition/__init__.py:1234:13: F401 'tensorflow.contrib.framework.python.ops.audio_ops as contrib_audio' imported but unused

**Comment by chriamue** [comment]
You can merge now. The needed tensorflow import depends on the model. So the user has to import
it himself, like in the tensorflow commands example.

**Comment by Uberi** [comment]
LGTM :+1:

**Pull request merged**
