### PR TITLE
exception_on_overflow broke program on Python2.7

### PR DESCRIPTION
**Pull request by michaelpri10**

### CODE REVIEW

**Comment by Uberi** [comment]
Thanks for the patch! The flag is needed, but v3.3.2 will no longer throw an exception when it's used; it needed a bit of a different solution.

**Comment by michaelpri10** [comment]
I still get the `TypeError: read() got an unexpected keyword argument 'exception_on_overflow'` when it runs even with the updated version.

**Comment by Uberi** [comment]
Hi @michaelpri10,

It seems like you have PyAudio 0.2.8. This library requires 0.2.9, so I recommend trying it with that version.

**Comment by michaelpri10** [comment]
Great catch! That worked, thanks!

**Pull request closed without merging**
